spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: users-service
          uri: http://localhost:8085/
          predicates:
            - Path=/users/**
        - id: movies-service
          uri: http://localhost:8087/
          predicates:
            - Path=/movies/**
        - id: billing-service
          uri: http://localhost:8086/
          predicates:
            - Path=/bills/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

  cloud:
    gateway:
      default-filters:
        - TokenRelay

server:
  port: 8082