spring:
  application:
    name: ms-bill
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/DigitalMedia
        registration:
          keycloak:
            client-id: microservicios
            client-secret: y4Q7a35oTtDygiMpdRhSN1kMUEyZGEe2
            scope: openid
            redirect_uri: http://localhost:8081/login/oauth2/code/google


server:
  port: 8086

eureka:
  instance:
    hostname: localhost
    instance-id: ms-bill
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
